"""Add digital signature fields

Revision ID: 0b60428d844b
Revises: 3233c55f1535
Create Date: 2024-11-15 05:19:43.770502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b60428d844b'
down_revision = '3233c55f1535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('initial_signature', sa.Text(), nullable=True))

    with op.batch_alter_table('forwards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signature_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forwards', schema=None) as batch_op:
        batch_op.drop_column('signature_message')
        batch_op.drop_column('signature')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('initial_signature')
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
