"""Add initial_signature_message to Document

Revision ID: 3139e6d16af4
Revises: 7378e39fefe6
Create Date: 2024-11-18 17:51:42.776485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3139e6d16af4'
down_revision = '7378e39fefe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('initial_signature_message', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'initial_signature_message')
    # ### end Alembic commands ###
