"""Modify User model for encrypted private keys

Revision ID: 3233c55f1535
Revises: c4653ebeb49e
Create Date: 2024-11-15 04:04:12.451042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3233c55f1535'
down_revision = 'c4653ebeb49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key_encrypted', sa.Text(), nullable=True))
        batch_op.drop_column('private_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', sa.TEXT(), nullable=True))
        batch_op.drop_column('private_key_encrypted')

    # ### end Alembic commands ###
