"""safe

Revision ID: 52e937c2679f
Revises: a13ed3c28986
Create Date: 2024-11-04 17:30:19.456612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e937c2679f'
down_revision = 'a13ed3c28986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=32), nullable=False))
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
