"""Create attachment model and update document model

Revision ID: 673415d79963
Revises: 755ee53c1d7c
Create Date: 2024-11-10 12:13:39.284220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673415d79963'
down_revision = '755ee53c1d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('attachments')
        batch_op.drop_column('attachment_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('attachments', sa.TEXT(), nullable=True))

    op.drop_table('attachments')
    # ### end Alembic commands ###
