"""新增加密欄位至 Document 模型

Revision ID: 7378e39fefe6
Revises: 0b60428d844b
Create Date: 2024-11-15 13:13:40.188598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7378e39fefe6'
down_revision = '0b60428d844b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_aes_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_encryption_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_documents_current_encryption_user_id_users',  # 外鍵名稱
            'users',                                         # 參照表名
            ['current_encryption_user_id'],                 # 當前表的欄位
            ['id']                                           # 參照表的欄位
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_current_encryption_user_id_users', type_='foreignkey')
        batch_op.drop_column('current_encryption_user_id')
        batch_op.drop_column('encrypted_aes_key')
        batch_op.drop_column('encrypted_content')

    # ### end Alembic commands ###