"""Add updated_at field to Document model

Revision ID: 755ee53c1d7c
Revises: c443e379b8f2
Create Date: 2024-11-06 13:21:19.611074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755ee53c1d7c'
down_revision = 'c443e379b8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
