"""Remove signature_content column

Revision ID: 8e269deaf3a3
Revises: 8b606559f079
Create Date: 2024-11-20 17:53:43.507202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e269deaf3a3'
down_revision = '8b606559f079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forwards', schema=None) as batch_op:
        batch_op.drop_column('signature_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forwards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_content', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
