"""Add encryption_log column to Document model

Revision ID: b4ed673d1922
Revises: 8e269deaf3a3
Create Date: 2024-11-29 23:42:41.734455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ed673d1922'
down_revision = '8e269deaf3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_log', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('encryption_log')

    # ### end Alembic commands ###
