"""Add security_leveld t



Revision ID: c443e379b8f2
Revises: bf35e0ecc208
Create Date: 2024-11-04 18:04:35.930174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c443e379b8f2'
down_revision = 'bf35e0ecc208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('attachment_description')

    # ### end Alembic commands ###
